### ISSUE TITLE
Sostituzione logo

### ISSUE THREAD

**Issue by ilgrosso** [Thelepest/syncopeProject#2]
L'esercizio diceva:

> Sostituire il logo standard di Syncope con [1], sia nella Admin Console sia nell'Enduser UI

Vedo la sostituzione nell'Enduser ma non nella Console

**Comment by Thelepest** [comment]
Sulla pagina della Admin Console (ispeziono da browser) trovo il riferimento all'immagine :

<img class="login-logo" src="img/logo-green.png">

Che non trovo sul codice (ho trovato solo quella relativa all'Enduser, in selfTemplate.html).

**Comment by Thelepest** [comment]
sostituzione effettuata con l'ultimo commit "logo changed on Admin Console"

**Comment by ilgrosso** [comment]
Intendi 21241536bbb8ac4342fab8bbcfd5d36fd0d8856f suppongo.

**Comment by Thelepest** [comment]
> Intendi [2124153](https://github.com/Thelepest/syncopeProject/commit/21241536bbb8ac4342fab8bbcfd5d36fd0d8856f) suppongo.

Esatto

**Comment by ilgrosso** [comment]
Verificato che i loghi sono stati sostituiti.
